// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfOl9CeEWx96uQ1MUCsJJn_LRbVJLOc2g',
    appId: '1:697301321773:web:cf9ba15d65032d9320d0a4',
    messagingSenderId: '697301321773',
    projectId: 'jobswipe-e3e3e',
    authDomain: 'jobswipe-e3e3e.firebaseapp.com',
    storageBucket: 'jobswipe-e3e3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4IlJMJXRL1xfNGK-bB9B8xgjuqv-3nL0',
    appId: '1:697301321773:android:0fec08dd969b9e5520d0a4',
    messagingSenderId: '697301321773',
    projectId: 'jobswipe-e3e3e',
    storageBucket: 'jobswipe-e3e3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgTDVYwMYmUfJFy7TKjr-d9UD2rFY3R4U',
    appId: '1:697301321773:ios:1a3e86180d1c439120d0a4',
    messagingSenderId: '697301321773',
    projectId: 'jobswipe-e3e3e',
    storageBucket: 'jobswipe-e3e3e.firebasestorage.app',
    androidClientId: '697301321773-13ltm5os7s92nv7pavhfqbsmg85go0id.apps.googleusercontent.com',
    iosClientId: '697301321773-rulfo2agq6dg80182cklhit7vmunucbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobswipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgTDVYwMYmUfJFy7TKjr-d9UD2rFY3R4U',
    appId: '1:697301321773:ios:1a3e86180d1c439120d0a4',
    messagingSenderId: '697301321773',
    projectId: 'jobswipe-e3e3e',
    storageBucket: 'jobswipe-e3e3e.firebasestorage.app',
    androidClientId: '697301321773-13ltm5os7s92nv7pavhfqbsmg85go0id.apps.googleusercontent.com',
    iosClientId: '697301321773-rulfo2agq6dg80182cklhit7vmunucbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobswipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfOl9CeEWx96uQ1MUCsJJn_LRbVJLOc2g',
    appId: '1:697301321773:web:0d4832920442723f20d0a4',
    messagingSenderId: '697301321773',
    projectId: 'jobswipe-e3e3e',
    authDomain: 'jobswipe-e3e3e.firebaseapp.com',
    storageBucket: 'jobswipe-e3e3e.firebasestorage.app',
  );
}
